// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTRmJPFmzQ1elAghu8WKDi7n3FYDehyWA',
    appId: '1:390548217658:web:8830907540498f5445ba03',
    messagingSenderId: '390548217658',
    projectId: 'bingeworthy-bw',
    authDomain: 'bingeworthy-bw.firebaseapp.com',
    storageBucket: 'bingeworthy-bw.appspot.com',
    measurementId: 'G-QR1XDWD48V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOk2ddRB1QWyU4JXmj_-uVsoZESW7mYyU',
    appId: '1:390548217658:android:93a59daef8ccbbcb45ba03',
    messagingSenderId: '390548217658',
    projectId: 'bingeworthy-bw',
    storageBucket: 'bingeworthy-bw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5ZamEcWqnHpkgevTN9eXD9DlpR6-8nk',
    appId: '1:390548217658:ios:aa6e02fb7b34378245ba03',
    messagingSenderId: '390548217658',
    projectId: 'bingeworthy-bw',
    storageBucket: 'bingeworthy-bw.appspot.com',
    iosClientId: '390548217658-70o1h9ng3dum8fnvpqoud6ulug83cf8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL5ZamEcWqnHpkgevTN9eXD9DlpR6-8nk',
    appId: '1:390548217658:ios:85f274182620d97945ba03',
    messagingSenderId: '390548217658',
    projectId: 'bingeworthy-bw',
    storageBucket: 'bingeworthy-bw.appspot.com',
    iosClientId: '390548217658-a79luc347j46u3noto827hftsts0eqnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.client.RunnerTests',
  );
}
